### ISSUE TITLE
Remove version checks and python 2 code

### ISSUE THREAD

**Issue by naveen-ram** [IBM/django-ibmi#13]
There are quite a number of checks done for the django version since we will be using 2.0+ support as well as python 3 support, the code for these checks and the code within them can be removed

**Comment by kadler** [comment]
This and #22 would be the next items I'd suggest working on.

**Comment by kadler** [comment]
In addition to python 2 checks, we can use the Python 3 `super()` call shortcut instead of listing the class name and self reference. See https://www.journaldev.com/15911/python-super
