### ISSUE TITLE
Rewrite CursorWrapper class to be compatible with pyodbc

### ISSUE THREAD

**Issue by naveen-ram** [IBM/django-ibmi#47]
In #21, all the instances of ibm_db were changed to pyodbc. Because of this, the CursorWrapper class must be rewritten to work with pyodbc rather than ibm_db. The reason for this being that the CursorWrapper had extended ibm_db.Cursor and now extends pyodbc.Cursor which cannot be extended as a static class.

**Comment by kadler** [comment]
Can you explain further what you mean by "pyodbc.Cursor [...] cannot be extended as a static class"?
